# Generated by Django 5.2 on 2025-05-09 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnimalAid',
            new_name='animalaid_db',
        ),
    ]
