# Generated by Django 5.2 on 2025-05-13 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_animalaid_animalaid_db'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='animalaid_db',
            new_name='api_test',
        ),
        migrations.AlterModelTable(
            name='api_test',
            table='animalaid_db',
        ),
    ]
