# Generated by Django 5.2 on 2025-05-13 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_animalaid_db_api_test_alter_api_test_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='api_test',
            table='api_test',
        ),
    ]
