# Generated by Django 5.2 on 2025-05-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='Brand',
            new_name='brand',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medicine_images/'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='unit',
            field=models.CharField(max_length=20),
        ),
    ]
