# Generated by Django 5.2 on 2025-05-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_rename_brand_medicine_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='generic_name',
            field=models.CharField(default=12345, max_length=100),
            preserve_default=False,
        ),
    ]
