# Generated by Django 5.2 on 2025-11-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_medicine_generic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='piece',
            field=models.IntegerField(default=0),
        ),
    ]
