# Generated by Django 5.2 on 2025-05-20 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('livestock', 'Livestock'), ('poultry', 'Poultry'), ('dairy', 'Dairy'), ('cattle', 'Cattle'), ('fish', 'Fish')], max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predicted_disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.disease')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='consultation_images/')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='consultations.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('diseases', models.ManyToManyField(related_name='medicines', to='consultations.disease')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='recommended_medicines',
            field=models.ManyToManyField(blank=True, to='consultations.medicine'),
        ),
    ]
