# Generated by Django 5.2 on 2025-10-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(choices=[('Poultry', 'Poultry'), ('Cow', 'Cow'), ('Bird', 'Bird'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='consultations/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='consultations/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='consultations/')),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
