# Generated by Django 5.2 on 2025-05-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='feed_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
