# Generated by Django 5.2 on 2025-11-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_feed_feed_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='piece',
            field=models.IntegerField(default=0),
        ),
    ]
