# Generated by Django 5.2 on 2026-04-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksale',
            name='customer_area',
            field=models.CharField(blank=True, default='', help_text='e.g. Dhaka, Chittagong, Sylhet', max_length=100),
        ),
        migrations.AddField(
            model_name='stocksale',
            name='customer_group',
            field=models.CharField(blank=True, default='', help_text='e.g. Farmer, Clinic, Retailer, Wholesale', max_length=100),
        ),
        migrations.AddField(
            model_name='stocksale',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='stocksale',
            name='customer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocksale',
            name='product_type',
            field=models.CharField(choices=[('medicine', 'Medicine'), ('feed', 'Feed')], max_length=10),
        ),
    ]
