# Generated by Django 5.2 on 2026-04-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stocksale_customer_area_stocksale_customer_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockpurchase',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='stocksale',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='stocksale',
            name='customer_area',
        ),
        migrations.RemoveField(
            model_name='stocksale',
            name='customer_group',
        ),
        migrations.AddField(
            model_name='stocksale',
            name='customer_address',
            field=models.CharField(blank=True, default='', help_text='Shipping/billing address from the order or payment record', max_length=500),
        ),
        migrations.AddField(
            model_name='stocksale',
            name='product_category',
            field=models.CharField(blank=True, default='', help_text='Medicine.category OR Feed.animal_category', max_length=100),
        ),
    ]
