# Generated by Django 5.2 on 2026-04-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_stockpurchase_options_alter_stocksale_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockpurchase',
            options={'ordering': ['-created_at'], 'verbose_name': 'Stock Purchase', 'verbose_name_plural': 'Stock Purchases'},
        ),
        migrations.AlterModelOptions(
            name='stocksale',
            options={'ordering': ['-created_at'], 'verbose_name': 'Stock Sale', 'verbose_name_plural': 'Stock Sales'},
        ),
        migrations.RemoveField(
            model_name='stocksale',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='stocksale',
            name='product_category',
        ),
        migrations.AddField(
            model_name='stocksale',
            name='customer_area',
            field=models.CharField(blank=True, default='', help_text='e.g. Dhaka, Chittagong, Sylhet', max_length=100),
        ),
        migrations.AddField(
            model_name='stocksale',
            name='customer_group',
            field=models.CharField(blank=True, default='', help_text='e.g. Farmer, Clinic, Retailer, Wholesale', max_length=100),
        ),
    ]
